### ISSUE TITLE
RSS feeds show incorrect date

### ISSUE THREAD

**Issue by josphh** [danth/coricamu#10]
### Current behaviour

Some posts shown via RSS show incorrect dates. For example, the RSS for [danth.pwak.org](https://danth.pwak.org) shows that 6 posts were published on the 10th of March at 18:41, while others are correct.

### Expected behaviour

For the correct date from the website to show with the post.

### Additional context

Using [Feeder](https://gitlab.com/spacecowboy/Feeder) RSS reader.

**Comment by danth** [comment]
Looks like dates need to be stored in RFC-822 format.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdanth.pwak.org%2Frss%2Fposts.xml
